{{ if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: longhorn
    role: alert-rules
  name: prometheus-longhorn-rules
spec:
  groups:
  - name: longhorn.rules
    rules:
    {{- if .Values.prometheusRule.defaultRules.enabled }}
      - alert: LonghornVolumeUsageCritical
        annotations:
          description:
            {{`Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% used for
            more than 5 minutes.`}}
          summary: Longhorn volume capacity is over 90% used.
        expr: 100 * (longhorn_volume_usage_bytes / longhorn_volume_capacity_bytes) > 90
        for: 5m
        labels:
          issue: {{`Longhorn volume {{$labels.volume}} usage on {{$labels.node}} is critical.`}}
          severity: critical
    {{- end }}
      {{- range .Values.prometheusRule.additionalRules }}
      - {{ . | toYaml | nindent 8 | trim }}
      {{- end }}
{{ end }}